#!/bin/bash

case $1 in
	start)
		UNITY=${2:-artful-server-cloudimg-amd64.img}
		start-stop-daemon -b --start --pidfile /tmp/unity --make-pidfile --startas /usr/bin/kvm -- \
			-m 1024 \
			-smp 1 \
			-vnc :10 \
			-serial stdio \
			-device e1000,netdev=user.0 \
			-netdev user,id=user.0,hostfwd=tcp::5555-:22 \
			-drive file=${UNITY},if=virtio,cache=writeback,index=0
		;;
	stop)
		start-stop-daemon --stop --pidfile /tmp/unity --remove-pidfile
		;;
	status)
		start-stop-daemon --status --pidfile /tmp/unity
		;;
esac
