#!/bin/sh

# set up autostart
ln -s /etc/init.d/processkiller /etc/rc2.d/S10processkiller
ln -s /etc/init.d/processkiller /etc/rc3.d/S10processkiller
ln -s /etc/init.d/processkiller /etc/rc4.d/S10processkiller
ln -s /etc/init.d/processkiller /etc/rc5.d/S10processkiller
