#!/bin/sh
### BEGIN INIT INFO
# Provides:          merlin
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       VirtUE Merlin
### END INIT INFO

SCRIPT="python /opt/merlin/merlin.py -l /opt/merlin/merlin.log -c /var/private/ssl/rethinkdb_cert.pem -v /var/private/ssl/virtue_1_key.pem -e /var/private/ssl/excalibur_pub.pem -r rethinkdb.galahad.com virtue_$(cat /etc/machine-id)"
RUNAS=merlin

PIDFILE=/opt/merlin/merlin.pid
LOGFILE=/opt/merlin/merlin-initd.log

start() {
  if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting service...' >&2
  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
  echo "Command: $CMD" >&2
  su -c "$CMD" $RUNAS > "$PIDFILE"
  echo 'Service started' >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service...' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac
