#!/bin/bash

#   Simple script for sending firewall commands to the
#   network actuator

usage(){ echo "USAGE: netblock [block|unblock] [incoming|outgoing] [ipv4|ipv6|tcp|udp] <value>"; }
args="$*"
command="$(echo $args | xargs)"
chardevice="/dev/netblockchar"
if [ ! -e "$chardevice" ]
then
	echo "Load netblock kernel module before running program."
	exit 1
fi

echo $command >> /dev/netblockchar 2>/dev/null
if [ $? -ne 0 ]
then
	usage
fi
