#!/bin/bash
systemctl daemon-reload
adduser --system --disabled-password --disabled-login --home /var/opt/excalibur \
                --no-create-home --quiet --force-badname --group excalibur
chown -R excalibur:excalibur /var/opt/excalibur
